---
- name: Get name of the vrouter container
  command: docker ps --filter name=vrouter-agent --format {%raw%}"{{.Names}}"{%endraw%}
  register: result_name
  tags:
    - cleanup

- name: Send QUIT signal to vrouter
  command:
    docker kill -s QUIT "{{ result_name.stdout }}"
  when:
    - result_name.stdout
  tags:
    - cleanup

- name: Stop and remove Vrouter Container and volumes
  docker_compose:
    project_src: /etc/contrail/vrouter
    state: absent
    remove_images: all
    remove_volumes: yes
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
  when:
    - result_name.stdout

- name: Delete all files and folders used by vrouter
  file:
    path: /etc/contrail/common_vrouter.env
    state: absent

- file:
    path: /etc/contrail/vrouter/
    state: absent
