---
- name: Install yum-utils
  yum:
     name: yum-utils
     state: present

- name: Add Docker repo
  command:
     cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: configure docker mirror
  yum_repository:
    name: docker_mirror
    description: Docker Mirror
    baseurl: '{{ docker_mirror_url }}'
    gpgcheck: no
  when: docker_mirror_url is defined

- name: install docker
  yum:
    name: docker-ce
  register: res
  retries: 5
  until: res is success
