---

- name : set params
  set_fact:
     toragent_name: "{{ toragent.key }}"
  with_dict: "{{ toragent_config |  default({}) }}"
  loop_control:
    loop_var: toragent
  when:
     - toragent_config is defined
     - toragent.key is defined

- name: Get name of the toragent container
  command: docker ps --filter name=^/{{toragent_name}} --format {%raw%}"{{.Names}}"{%endraw%}
  register: result_name
  tags:
    - cleanup

- name: Send QUIT signal to toragent
  command:
    docker kill -s QUIT "{{ result_name.stdout }}"
  when:
    - result_name.stdout
  tags:
    - cleanup

- name: Stop and remove toragent Container and volumes
  docker_compose:
    project_src: /etc/contrail/{{ toragent_name }}
    state: absent
    remove_images: all
    remove_volumes: yes
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
  when:
    - result_name.stdout

- name: Delete all files and folders used by toragent
  file:
    path: /etc/contrail/{{ toragent_name }}.env
    state: absent

- file:
    path: /etc/contrail/{{ toragent_name }}/
    state: absent
