---
- name: create /etc/contrail/redis
  file:
    path: /etc/contrail/redis
    state: directory
    recurse: yes

- name: "Set variables for Stunnel"
  set_fact:
    redis_ssl_enable: "{{ contrail_configuration.REDIS_SSL_ENABLE | default(contrail_configuration.SSL_ENABLE | default('no')) | bool }}"

- name: update image
  shell: "docker pull {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}"
  with_items:
    - contrail-external-redis
    - contrail-external-stunnel
  when: contrail_configuration.UPDATE_IMAGES is undefined or contrail_configuration.UPDATE_IMAGES != false

- name: "create redis compose file"
  template:
    src: contrail-redis.yaml.j2
    dest: "/etc/contrail/redis/docker-compose.yaml"

- name: "start redis"
  docker_service:
    project_src: /etc/contrail/redis
