---
- name: create /etc/contrail/redis
  file:
    path: /etc/contrail/redis
    state: directory
    recurse: yes

- name: "Set variables for Stunnel"
  set_fact:
    redis_ssl_enable: "{{ contrail_configuration.REDIS_SSL_ENABLE | default(contrail_configuration.SSL_ENABLE | default('no')) | bool }}"

- name: "create redis compose file"
  template:
    src: contrail-redis.yaml.j2
    dest: "/etc/contrail/redis/docker-compose.yaml"

- name: "start redis"
  docker_compose:
    project_src: /etc/contrail/redis
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
