---
- name: create /etc/contrail/analytics_alarm
  file:
    path: /etc/contrail/analytics_alarm
    state: directory
    recurse: yes

- name: set zookeeper nodes to CONFIGDB_NODES if defined
  set_fact:
    zookeeper_nodes: "{{ contrail_configuration.CONFIGDB_NODES }}"
  when: contrail_configuration.CONFIGDB_NODES is defined

- name: set zookeeper nodes to CONTROLLER_NODES if CONFIGDB_NODES not defined
  set_fact:
    zookeeper_nodes: "{{ contrail_configuration.CONTROLLER_NODES }}"
  when: contrail_configuration.CONTROLLER_NODES is defined and contrail_configuration.CONFIGDB_NODES is undefined

- name: create contrail analytics_alarm docker-compose file
  template:
    src: contrail-analytics-alarm.yaml.j2
    dest: /etc/contrail/analytics_alarm/docker-compose.yaml

- name: start contrail analytics_alarm
  docker_compose:
    project_src: /etc/contrail/analytics_alarm
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
