---
- name: stop contrail analyticsdb
  docker_compose:
    project_src: /etc/contrail/analytics_database
    state: absent
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
